### ISSUE TITLE
Issue with proxy settings

### ISSUE THREAD

**Issue by JeevanCK7** [open-ness/specs#26] opened 2020-05-27 14:46 UTC
Can somebody help me to understand the need of group_vars/all.yml file ? I have set proxy_os_enable: false
But what should other proxy_ variables contain? Please help me in understanding this

**Comment by amr-mokhtar** [comment] 2020-05-27 16:00
Duplicate of https://github.com/open-ness/edgecontroller/issues/31

**Closed as completed by amr-mokhtar** 2020-05-27 16:00 UTC
