### ISSUE TITLE
Issue with kubectl command

### ISSUE THREAD

**Issue by JeevanCK7** [open-ness/specs#25] opened 2020-05-27 14:44 UTC
I have completed bringing up controller and edge node. While I'm trying to work with kubectl command. I'm getting the below error.

kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: proxyconnect tcp: dial tcp: lookup proxy.example.org on 172.16.2.31:53: no such host

**Comment by amr-mokhtar** [comment] 2020-05-27 15:57
Duplicate of https://github.com/open-ness/edgecontroller/issues/30

**Closed as completed by amr-mokhtar** 2020-05-27 15:57 UTC
