### ISSUE TITLE
Issue while running OpenVino application

### ISSUE THREAD

**Issue by splendid18** [open-ness/specs#15] opened 2020-03-09 09:35 UTC
I have followed and completed the setup for the OpenVino application as told in the documentation. After running the last ./run-docker.sh script I am not getting the pop up window with the video runnning even after rectifying the errors as told so in the documentation. I am getting the following warning on the screen, could you please help @amr-mokhtar 

--------------------------------------------------------------------------------------------------
/run-docker.sh
ffplay version 2.8.15 Copyright (c) 2003-2018 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-36)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-gnutls --enable-ladspa --enable-libass --enable-libcdio --enable-libdc1394 --enable-libfdk-aac --enable-nonfree --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libx264 --enable-libx265 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-runtime-cpudetect
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default
[sdp @ 0x7f94b4000920] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
downstream.sdp: could not find codec parameters
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0
./tx_video.sh
--------------------------------------------------------------------------------------------------

**Comment by splendid18** [comment] 2020-03-09 09:45
Also the traffic host in my setup is INTEL nuc model number NUC5i5RYH. Is this an audio codec not supported issue which we need to handle?

**Comment by tongtongxiaopeng1979** [comment] 2020-03-19 09:34
on the client machine, install wireshark and check whether the port 5001 receive the traffic.
and need to check whether there is "host administratively prohibited" error.

 
If caused by "host adminstratively prohibited", need to 
disable firewalld service as:

systemctl stop firewalld.service

or 
>  firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT 0 -p udp --dport 5001 -j ACCEPT
>  firewall-cmd --reload

**Comment by amr-mokhtar** [comment] 2020-04-06 18:13
Hi @ashurvcs,
Can you try using longer video files in the client-sim docker? It could be that the traffic is transmitted but becuase of the high rate of switching is causing the pop-up window not appearing.

**Comment by ishanVshah** [comment] 2020-06-05 18:43
Hi @ashurvcs @amr-mokhtar @tongtongxiaopeng1979  can anyone help me on this. I am facing error to run openVINO with NE OpenNESS 20.3 CE..

No protocol specified
No protocol specified
Could not initialize SDL - No available video device
(Did you set the DISPLAY variable?)
./tx_video.sh

**Comment by ishanVshah** [comment] 2020-07-16 17:32
Hi @amr-mokhtar i am facing the same error in openness network edge 20.06

link reference : 
https://github.com/open-ness/specs/blob/master/doc/applications-onboard/network-edge-applications-onboarding.md#onboarding-openvino-application

Point No. 1:
-> Verify that openvino.openness is correctly resolved (ANSWER section should contain IP of Edge DNS).
dig openvino.openness show me the IP Address of OpenVINO consumer application instead of Edge DNS.

Point No. 2:
I have x11 terminal and error screenshot is attached of client-sim machine.
![image](https://user-images.githubusercontent.com/59759055/87703407-717abb00-c7b8-11ea-9bd0-c26556b7a5da.png)

**Comment by ishanVshah** [comment] 2020-07-16 17:34
![image](https://user-images.githubusercontent.com/59759055/87703491-940cd400-c7b8-11ea-9a0d-d1d7dab9ec4c.png)

image is blur so, sending logs of client-sim container.

**Comment by ishanVshah** [comment] 2020-07-16 18:59
Hi @amr-mokhtar  after applying some changes in environment, proceed further but pop-up is not coming UP.

requesting you to please help me here on this.

![image](https://user-images.githubusercontent.com/59759055/87711044-5e6de800-c7c4-11ea-8f3a-85da2acc8d6d.png)

**Comment by amr-mokhtar** [comment] 2020-07-17 09:41
Hi @ishanVshah , I will replicate on my setup and see if I can re-produce the issue. Will circle back on this.

**Comment by ishanVshah** [comment] 2020-07-17 13:24
@amr-mokhtar it would be great if you help me on this.

**Comment by ishanVshah** [comment] 2020-07-18 10:57
@amr-mokhtar  kindly close this issue as openvino application on-board successfully on network-edge openness.

issue of xterm window and display variable issue.

thanks for your great support.

**Comment by ishanVshah** [comment] 2020-07-20 05:51
@amr-mokhtar  kindly close this issue as openvino application on-board successfully on network-edge openness.

issue of xterm window and display variable issue.

thanks for your great support.

**Closed as completed** 2020-07-20 08:45 UTC
Labels: help wanted, OpenNESS-1912
